version: '1.0'
name: 'doc-navigator-project'

services:
  frontend:
    image: doc-navigator/frontend/node:20-slim
    container_name: frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    stdin_open: true
    tty: true
    restart: unless-stopped
